export const initialProductState = {
  // id: '',
  barcode_number: '',
  barcode_formats: '',
  mpn: '',
  model: '',
  asin: '',
  title: '',
  category: '',
  manufacturer: '',
  brand: '',
  contributors: [],
  age_group: '',
  nutrition_facts: '',
  energy_efficiency_class: '',
  color: '',
  gender: '',
  material: '',
  pattern: '',
  format: '',
  multipack: '',
  size: '',
  length: '',
  width: '',
  height: '',
  weight: '',
  release_date: '',
  description: '',
  features: '',
  images: [],
  stores: '',
  reviews: '',
}

export const initialIngredientState = {
  nutrientId: 0,
  nutrientName: '',
  nutrientNumber: '',
  unitName: '',
  derivationCode: '',
  derivationDescription: '',
  derivationId: 0,
  value: 0,
  foodNutrientSourceId: 0,
  foodNutrientSourceCode: '',
  foodNutrientSourceDescription: '',
  rank: 0,
  indentLevel: 0,
  foodNutrientId: 0,
  dataPoints: 0,
}
